version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: "turing"
      POSTGRES_USER: "iNaz07"
      POSTGRES_PASSWORD: "Hello.Alem01"
    ports:
      - "5432:5432"

networks:
  intranet: